#! /usr/bin/env python

#
# Copyright (c) 2015 Google Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the names of its
# contributors may be used to endorse or promote products derived from this
# software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

## Tool to compare Toshiba test result folder file against the response folders
#

from __future__ import print_function
from os import listdir, walk
from os.path import isfile, join
import sys
import argparse
from chklog import compare_log_to_resp

# Program return values
PROGRAM_SUCCESS = 0
PROGRAM_WARNINGS = 1
PROGRAM_ERRORS = 2


def load_file(filename):
    """ Load a file into a list """
    with open(filename, "r") as f:
        return f.readlines()


def process_log_file(dirpath, filenames):
    print("dirpath", dirpath, "logfiles:", filenames) #*****
    # Extract the test name from the dirpath
    #***** TBD *****

    # If there's a corresponding test in the reponses folder,
    # run the comparisons for response-file and response-dme
    #***** TBD *****


def main():
    """Mainline"""

    parser = argparse.ArgumentParser()

    # Capture-specific args:
    parser.add_argument("--log",
                        required=True,
                        help="The log folder to compare")

    parser.add_argument("--es3",
                        required=True,
                        help="The es3-test folder to compare against")

    args = parser.parse_args()

    #logfiles = [ f for f in listdir(args.log) if isfile(join(args.log,f)) ]
    f = []
    for (dirpath, dirnames, filenames) in walk(args.log):
        process_log_file(dirpath, filenames)
        f.extend(filenames)

    sys.exit(PROGRAM_SUCCESS)


## Launch main
#
if __name__ == '__main__':
    main()
