#! /usr/bin/env python

#
# Copyright (c) 2015 Google Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the names of its
# contributors may be used to endorse or promote products derived from this
# software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

## Tool to compare a log file against a response file
#

from __future__ import print_function
import os
import sys
import argparse
from chklog import compare_log_to_resp

# Program return values
PROGRAM_SUCCESS = 0
PROGRAM_WARNINGS = 1
PROGRAM_ERRORS = 2


def load_file(filename):
    """ Load a file into a list """
    with open(filename, "r") as f:
        return f.readlines()


def main():
    """Mainline"""

    parser = argparse.ArgumentParser()

    # Capture-specific args:
    parser.add_argument("--log",
                        required=True,
                        help="The log file to compare")

    parser.add_argument("--resp",
                        required=True,
                        help="The response file to compare against")

    args = parser.parse_args()

    log = load_file(args.log)
    resp = load_file(args.resp)
    missing_response = compare_log_to_resp(log, resp)
    if missing_response:
        print("Log {0:s} failed: missing '{1:s}' in {2:s}".
              format(os.path.basename(args.log), missing_response,
                     os.path.basename(args.resp)))
    else:
        print("Log {0:s} passed rsp {1:s}".
              format(os.path.basename(args.log), os.path.basename(args.resp)))
    sys.exit(PROGRAM_SUCCESS)


## Launch main
#
if __name__ == '__main__':
    main()
