#! /usr/bin/env python

#
# Copyright (c) 2015 Google Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the names of its
# contributors may be used to endorse or promote products derived from this
# software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

from __future__ import print_function
import sys
import argparse
import errno
from tftf import Tftf, TFTF_SECTION_TYPE_RAW_CODE, \
    TFTF_SECTION_TYPE_RAW_DATA, TFTF_SECTION_TYPE_MANIFEST, \
    TFTF_HDR_NUM_SECTIONS, \
    TFTF_HEADER_SIZE_MIN, TFTF_HEADER_SIZE_MAX, TFTF_HEADER_SIZE_DEFAULT
from util import error
import io
from elftools.elf.elffile import ELFFile

DEFAULT_ARA_BOOT_STAGE = 2
DEFAULT_ARA_VID = 0
DEFAULT_ARA_PID = 0

# Flag to indicate that the last arg parsed was a section type, which
# means that an optional section parameters are now legal
allow_section_parameters = False


# the list of sections
sections = []


def auto_int(x):
    # Workaround to allow hex numbers to be entered for numeric arguments.
    return int(x, 0)


class SectionAction(argparse.Action):
    """argparse custom action for handling elements and subparameters"""

    def __call__(self, parser, namespace, values, option_string=None):
        global allow_section_parameters, sections
        if option_string in "--load --class --id":
            if not allow_section_parameters:
                error(option_string,
                      "can only follow --code, --data or --manifest")
            else:
                if option_string == "--load":
                    sections[-1]['load'] = values
                elif option_string == "--class":
                    sections[-1]['class'] = values
                elif option_string == "--id":
                    sections[-1]['id'] = values
        else:
            # Close the window on section load addresses
            allow_section_parameters = False

            # Handle the specific file type. In all cases, we stage the
            # section in a temporary holding variable to allow the
            # optional "--load_address" to be added to it.
            if option_string == "--code":
                sections.append({'type': TFTF_SECTION_TYPE_RAW_CODE,
                                 'file': values})
                allow_section_parameters = True
            elif option_string == "--data":
                sections.append({'type': TFTF_SECTION_TYPE_RAW_DATA,
                                 'file': values})
                allow_section_parameters = True
            elif option_string == "--manifest":
                sections.append({'type': TFTF_SECTION_TYPE_MANIFEST,
                                 'file': values})
                allow_section_parameters = True
            else:
                print("Unknown option '", option_string, "'")


class ElfFileAction(argparse.Action):
    """argparse custom action for handling ELF image files"""

    def __call__(self, parser, namespace, values, option_string=None):
        global sections
        try:
            with io.open(values, 'rb') as elf_file:
                image = ELFFile(elf_file)
                elf_sections = []
                code_section = image.get_section_by_name('.text')
                if code_section:
                    namespace.load = code_section['sh_addr']
                    elf_sections.append({'type': TFTF_SECTION_TYPE_RAW_CODE,
                                        'load': code_section['sh_addr'],
                                        'buffer': code_section.data()})
                data_section = image.get_section_by_name('.data')
                if data_section:
                    elf_sections.append({'type': TFTF_SECTION_TYPE_RAW_DATA,
                                        'load': data_section['sh_addr'],
                                        'buffer': data_section.data()})
                assert(code_section is not None or data_section is not None)
                sections += elf_sections
                if namespace.start == 0:
                    namespace.start = image['e_entry']
        except IOError as e:
            error(option_string, " must be followed by an ELF image!")
        except Exception as e:
            error(e)


def validate_args(args, sections):
    # Sanity-check the command line args and return a "valid" flag
    success = True
    if not sections:
        error("You need at least one --code, --data, --manifest or --elf!")
        success = False

    # Valdate the header size
    if (args.header_size < TFTF_HEADER_SIZE_MIN) or \
       (args.header_size > TFTF_HEADER_SIZE_MAX):
        error("--header_size is out of range ({0:d}-{1:d})".
              format(TFTF_HEADER_SIZE_MIN, TFTF_HEADER_SIZE_MAX))
        success = False
    if (args.header_size % 4) != 0:
        error("--header_size must be a multiple of 4")
        success = False

    if len(sections) > TFTF_HDR_NUM_SECTIONS:
        error("Too many sections -", TFTF_HDR_NUM_SECTIONS, "max.")
        success = False
    if args.start < 0 or args.start > 0xffffffff:
        error("--start is out of range")
        success = False
    if args.unipro_mfg < 0 or args.unipro_mfg > 0xffffffff:
        error("--unipro_mfg is out of range")
        success = False
    if args.unipro_pid < 0 or args.unipro_pid > 0xffffffff:
        error("--unipro_pid is out of range")
        success = False
    if args.ara_vid < 0 or args.ara_vid > 0xffffffff:
        error("Error: --ara_vid is out of range")
        success = False
    if args.ara_pid < 0 or args.ara_pid > 0xffffffff:
        error("--ara_pid is out of range")
        success = False
    if args.ara_stage < 1 or args.ara_stage > 3:
        error("--ara-stage is out of range")
        success = False

    if not args.out:
        args.out = 'ara:{:08x}:{:08x}:{:08x}:{:08x}:{:02x}.tftf'.format(
                   args.unipro_mfg, args.unipro_pid, args.ara_vid,
                   args.ara_pid, args.ara_stage)
    # TODO: Other checks TBD
    return success


def main():
    """Application for creating Trusted Firmware Transfer Format (TFTF) files

    This is covered in detail in "ES3 Bridge ASIC Boot ROM High Level Design".

    Usage: create-tftf --start <num> --out <file> {--header-size <num>} \
           {--name <string>} {--unipro-mfg} {--unipro-pid} \
           {--ara-vid} {--ara-pid} {--ara-stage} \
           {-v | --verbose} {--map} {--header-size}\
           [<section_type> <file> {--load <num>} --class <num>} --id <num>}]...
    Where:
        --start
            The memory location of the package entry point.
        --out
            Specifies the output file
        --header-size
            The size of the generated TFTF header, in bytes (512)
        --name
            Package name
        --unipro-mfg
            Unipro ASIC manufacturer ID
        --unipro-pid
            Unipro ASIC product ID
        --ara-vid
            ARA vendor ID
        --ara-pid
            ARA product ID
        --ara-stage
            ARA boot stage
        -v | --verbose
            Display the TFTF header and a synopsis of each TFTF section
        --map
            Create a map file of the TFTF header and each TFTF section
        <section_type>
            Specifies a file for a given type of section:
            --code        code section.
            --data        data section.
            --manifest    manifest section.
            --Certificate manifest section.
            Sections are nomally loaded contiguously, starting at --load.
        --load
            Set the address of the start of the section to <num>
        --class
            Set the section class to <num>
        --id
            Set the section id to <num>
    """

    parser = argparse.ArgumentParser()
    success = True

    # args that consume files
    parser.add_argument("--code",
                        action=SectionAction,
                        help="The name of an input firmware file")

    parser.add_argument("--data",
                        action=SectionAction,
                        help="The name of an input data file")

    parser.add_argument("--manifest",
                        action=SectionAction,
                        help="The name of an input manifest file")

    parser.add_argument("--elf",
                        action=ElfFileAction,
                        help="The name of an input ELF image file")

    # Per-section numeric args
    parser.add_argument("--class",
                        action=SectionAction,
                        type=auto_int,
                        default=0,
                        help="The class of the preceding TFTF section")

    parser.add_argument("--id",
                        action=SectionAction,
                        type=auto_int,
                        default=0,
                        help="The ID of the preceding TFTF section")

    parser.add_argument("--load", "--load_address",
                        action=SectionAction,
                        type=auto_int,
                        default=-1,
                        help="The load address for the preceding section")

    # Flags args
    parser.add_argument("-v", "--verbose",
                        action='store_true',
                        help="Dump the TFTF header when done")

    parser.add_argument("--map", "-m",
                        action='store_true',
                        help="displays the field offsets")

    # String/file args
    parser.add_argument("--name",
                        help="The firmware package name")

    parser.add_argument("--out",
                        help="The TFTF output filename")

    # Numeric args
    parser.add_argument("--start",
                        type=auto_int,
                        default=0,
                        help="The TFTF start address (code entry point)")

    parser.add_argument("--unipro-mfg",
                        type=auto_int,
                        default=0,
                        help="The UniPro manufacturer-ID")

    parser.add_argument("--unipro-pid",
                        type=auto_int,
                        default=0,
                        help="The UniPro product-ID")

    parser.add_argument("--ara-vid",
                        type=auto_int,
                        default=DEFAULT_ARA_VID,
                        help="The ARA vendor-ID")

    parser.add_argument("--ara-pid",
                        type=auto_int,
                        default=DEFAULT_ARA_PID,
                        help="The ARA product-ID")

    parser.add_argument("--ara-stage",
                        type=auto_int,
                        default=DEFAULT_ARA_BOOT_STAGE,
                        help="The ARA boot stage")

    parser.add_argument("--header-size",
                        type=auto_int,
                        default=TFTF_HEADER_SIZE_DEFAULT,
                        help="The size of the generated TFTF header, "
                             "in bytes (512)")

    args = parser.parse_args()

    # Sanity-check the arguments
    if not validate_args(args, sections):
        error("Invalid args")
        sys.exit(errno.EINVAL)

    # Populate the TFTF header from the command line args
    tftf_header = Tftf(args.header_size)
    tftf_header.firmware_package_name = args.name
    if args.load != 0:
        tftf_header.load_base = args.load
    else:
        error("No loading address specified.")
        sys.exit(errno.EINVAL)
    if args.start != 0:
        tftf_header.start_location = args.start
    else:
        error("No entry point specified.")
        sys.exit(errno.EINVAL)
    tftf_header.unipro_mfg_id = args.unipro_mfg
    tftf_header.unipro_pid = args.unipro_pid
    tftf_header.ara_vid = args.ara_vid
    tftf_header.ara_pid = args.ara_pid
    for section in sections:
        if 'file' in section:
            success = tftf_header.add_section_from_file(section['type'],
                                                        section.get('class',
                                                                    0),
                                                        section.get('id', 0),
                                                        section['file'],
                                                        section.get('load', 0))
            if not success:
                error("Too many sections")
                sys.exit(errno.EFBIG)
        elif 'buffer' in section:
            success = tftf_header.add_section(section['type'],
                                              section.get('class', 0),
                                              section.get('id', 0),
                                              section['buffer'],
                                              section.get('load', 0))
            if not success:
                error("Too many sections")
                sys.exit(errno.EFBIG)

    # Make the TFTF header internally consistent
    tftf_header.post_process()

    # Write the TFTF file (i.e., header and section files)
    if not tftf_header.write(args.out):
        sys.exit(errno.EIO)

    # Optionally display the header info
    if args.verbose:
        tftf_header.display(args.out)
        tftf_header.display_data(args.out)
    if args.map:
        tftf_header.create_map_file(args.out, 0)

    print("Done")

## Launch main
#
if __name__ == '__main__':
    main()
