#! /usr/bin/env python

#
# Copyright (c) 2015 Google Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the names of its
# contributors may be used to endorse or promote products derived from this
# software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

"""This script displays a TFTF header or file(s)"""

from __future__ import print_function
import sys
import argparse
import errno
from tftf import Tftf
from util import error

# Program return values
PROGRAM_SUCCESS = 0
PROGRAM_WARNINGS = 1
PROGRAM_ERRORS = 2


def main():
    """Application for displayijg Trusted Firmware Transfer Format (TFTF) files

    This is covered in detail in "ES3 Bridge ASIC Boot ROM High Level Design".

    Usage: display-tftf {-v} <file>...
    Where:
        -v | --verbose
            Display a synopsis of each TFTF section in addition to the TFTF\
            header
    """
    parser = argparse.ArgumentParser()

    # Flags args
    parser.add_argument("-v", "--verbose",
                        action='store_true',
                        help="adds more detail")

    parser.add_argument("files",
                        metavar='N',
                        nargs='+',
                        help="adds more detail")

    args = parser.parse_args()

    if not args.files:
        error("Missing files to display")
        sys.exit(errno.EINVAL)

    # Walk the list of files
    for f in args.files:
        tftf_header = Tftf(f)
        tftf_header.display(f)
        if args.verbose:
            tftf_header.display_data(f)


## Launch main
#
if __name__ == '__main__':
    main()
