#!/bin/bash
#
# Copyright (c) 2015 Google Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the names of its
# contributors may be used to endorse or promote products derived from this
# software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#------------------------------------------------------------------------------
# Make all 3 images, their TFTF files, and  FFFF file, and the bootrom image.
#
# Usage:
#    make3 {-es2tsb | -es3tsb | -fpgatsb } {-sign} {-v} {-dbg} \
#          {-nocrypto} {-gearchange} {-nodelay} {-debugmsg} {-handshake} \
#          {-stby} {-stby-wait-svr} {-stby-gbboot}  {-342}
#
#    -es2tsb, -es3tsb, -fpgatsb
#              Select the build target
#    -sign     Sign both level 2 & 3 firmware
#    -dbg      Compile with debugging symbols
#    -v        Verbose mode on TFTF creation
#    -prod     Enable _PRODUCTION mode for all 3 firmware levels
#
# TESTING parameters:
#    -nocrypto		Substitute fake cryptographic routines to speed simulation
#    -gearchange	Test for changing UniPro gear change
#    -nodelay		Disable a 100 ms delay after loading from SPI
#    -debugmsg		Allow debug serial output
#    -handshake		GPIO handshake with simulation/test controller
#    -342		Substitute the L3FW for L2FW to speed simulation
#------------------------------------------------------------------------------

# Make the s3FW, s2FW and the FFFF
makef4 $*

# Make the s1FW (aka BootRom)
makeboot $*

