#!/bin/bash
#
# Copyright (c) 2015 Google Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the names of its
# contributors may be used to endorse or promote products derived from this
# software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#------------------------------------------------------------------------------
# Make the GBFW server.
#
# Usage:
#    make3 {-es2tsb | -es3tsb | -fpgatsb } {-prod} {-gearchange}
#
#    -es2tsb, -es3tsb, -fpgatsb
#			Select the build target
#    -prod		Enable _PRODUCTION mode for all 3 firmware levels
#    -gearchange	Test for changing UniPro gear change
#------------------------------------------------------------------------------
BuildRoot=~/work/bootrom
BuildDir=~/work/bootrom/build
BinDir=~/work/bootrom/binary

#-----
# Process any args
#-----
Production=false
for arg in "$@" ; do    # arg will be each positional parameter
     if [[ ${arg} == "-es2tsb" ]]; then    # select target configuration
        CONFIG_CHIP="es2tsb"
     elif [[ ${arg} == "-es3tsb" ]]; then  # select target configuration
        CONFIG_CHIP="es3tsb"
     elif [[ ${arg} == "-fpgatsb" ]]; then # select target configuration
        CONFIG_CHIP="fpgatsb"
     elif [[ ${arg} == "-prod" ]]; then    # _PRODUCTION version
        Production=true
    elif [[ ${arg} == "-gearchange" ]]; then
        # Test for changing UniPro gear change
        GearChangeTest="${arg} "
    else
        echo "unknown arg $arg"
        exit 1
    fi
done

# Configure for a specific chip/target
$BuildRoot/configure ${CONFIG_CHIP}

# Export the various settings so that makefile will see them
export BUILD_FOR_GBBOOT_SERVER=1
if $GearChangeTest; then
    export _GEAR_CHANGE_TEST=1
fi
if $Production; then
    export _PRODUCTION=1
else
    export _PRODUCTION=0
fi



#-----
# Make the APBridge/server
#-----
echo "Make the GBBOOT server..."
make clean
make gbboot_server
pushd $BuildDir
mv bootrom.bin "gbboot_server.bin"
if [ -f bootrom.hex ]; then
    mv bootrom.hex "gbboot_server.hex"
fi
    mv bromcAP.dat "bromcAP_server.dat"
    mv bromcGP.dat "bromcGP_server.dat"
popd

echo "Done"

