#!/bin/bash
#
# Copyright (c) 2015 Google Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the names of its
# contributors may be used to endorse or promote products derived from this
# software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#------------------------------------------------------------------------------
# Make cannonical L2FW and L3FW images, their TFTF files, and  FFFF file.
#
# Usage:
#    makef4norm {-es2tsb | -es3tsb | -fpgatsb } {-sign} {-v} \
#               {-handshake}  {-stby} {-stby-wait-svr} {-stby-gbboot} \
#               {-spec `<num>`} {-342}
#
#    -es2tsb, -es3tsb, -fpgatsb
#              Select the build target
#    -sign     Sign both level 2 & 3 firmware
#    -v        Verbose mode on TFTF creation
#    -prod     Enable _PRODUCTION mode for all 3 firmware levels
#
# TESTING parameters:
#    -handshake		GPIO handshake with simulation/test controller
#    -stby		Enable standby-mode tesing
#    -stby-wait-svr	Will wait for the server in standby mode
#    -stby-gbboot	Enable GBBoot server standby mode
#    -spec <num>	Compile special test number `<num>`.
#    -342		Substitute the L3FW for L2FW to speed simulation
#------------------------------------------------------------------------------
BuildRoot=~/work/bootrom
BuildDir=~/work/bootrom/build
BinDir=~/work/bootrom/binary
KeyDir=~/bin

#-----
# Process any args
#-----
Production=false
DebugMode=false
Testing=false
NoCrypto=false
NoClr=false
DebugMessages=false
Handshake=false
StandbyTest=false
StandbyWaitForServer=false
GBBootServerStandby=false
SpecialTest=false
CryptoSuffix="-crypto"
DbgSuffix="-quiet"
HandshakeSuffix=""
SymbolSuffix="opt"
for arg in "$@" ; do    # arg will be each positional parameter
    if $SpecialTest; then
        # The previous arg was "-spec", so pick up the special test no.
        SpecialTestNum=${arg}
        HaveSpecialTest=true
        SpecialTest=false
        Handshake=true  # (Special test implies -handshake)
    elif [[ ${arg} == "-spec" ]]; then
        # Take the next arg as a special test number
        SpecialTest=true
    elif [[ ${arg} == "-sign" ]]; then    # Sign the 2nd & 3rd level Firmware?
        Sign=${arg}
    elif [[ ${arg} == "-dbg" ]]; then     # Compile with debugging symbols
        DebugMode=true
        SymbolSuffix="-debug"
    elif [[ ${arg} == "-es2tsb" ]]; then  # select target configuration
        CONFIG_CHIP="es2tsb"
    elif [[ ${arg} == "-es3tsb" ]]; then  # select target configuration
        CONFIG_CHIP="es3tsb"
    elif [[ ${arg} == "-fpgatsb" ]]; then # select target configuration
        CONFIG_CHIP="fpgatsb"
    elif [[ ${arg} == "-prod" ]]; then    # Compile all levels for Toshba Simulation
        Production=true
    elif [[ ${arg} == "-v" ]]; then       # TFTF verbose mode
        Verbose=${arg}
    # Test args
    elif [[ ${arg} == "-nocrypto" ]]; then
        # Substitute fake cryptographic routines to speed simulation
        Testing=true
        NoCrypto=true
        CryptoSuffix="-nc"
    elif [[ ${arg} == "-noclr" ]]; then
        # Clear only the minimum amount of RAM to speed simulation
        Testing=true
        NoClr=true
    elif [[ ${arg} == "-debugmsg" ]]; then
        # Allow debug serial output
        Testing=true
        DebugMessages=true
        DbgSuffix="-uart"
    elif [[ ${arg} == "-handshake" ]]; then
        # GPIO handshake with simulation/test controller
        Handshake=true
    elif [[ ${arg} == "-stby" ]]; then
        #    -handshake	GPIO handshake with simulation/test controller
        Testing=true
        StandbyTest=true
    elif [[ ${arg} == "-stby-wait-svr" ]]; then
        #    -handshake	GPIO handshake with simulation/test controller
        Testing=true
        StandbyWaitForServer=true
    elif [[ ${arg} == "-stby-gbboot" ]]; then
        #    -handshake	GPIO handshake with simulation/test controller
        Testing=true
        GBBootServerStandby=true
    elif [[ ${arg} == "-342" ]]; then
        # Substitute the L3FW for L2FW to speed simulation
        Subst342=${arg}
    else
        echo "make3: unknown arg $arg"
        exit 1
    fi
done

# Fill in missing chip
if [ ! $CONFIG_CHIP ]; then
    echo "CONFIG_CHIP not set, assuming $DEFAULT_CHIP_CONFIG"
    CONFIG_CHIP=$DEFAULT_CHIP_CONFIG
fi

# We have GPIO handshake mode if explicitly -handshake or implicitly by -spec
if $Handshake; then
    Testing=true
    HandshakeSuffix="-hs"
fi


makef4 -$CONFIG_CHIP -dbg -nocrypto -noclr -nodelay -debugmsg -handshake $Verbose \
        $Sign $Subst342 \
       -stby -stby-wait-svr -stby-gbboot

