#!/bin/bash
#
# Copyright (c) 2015 Google Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the names of its
# contributors may be used to endorse or promote products derived from this
# software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#------------------------------------------------------------------------------
# Make the FFFF file and create an es3-test folder containing the test suite
# resources
#
# Usage:
#    makeall {-es2tsb | -es3tsb | -fpgatsb } {-v} {-justboot} \
#          {-nocrypto} {-noclr} {-debugmsg} {-handshake} \
#          {-stby} {-stby-wait-svr} {-stby-gbboot} {-342}
#
#    -es2tsb, -es3tsb, -fpgatsb
#                        Select the build target
#    -v                  Verbose mode on TFTF creation
#
# TESTING parameters:
#    -342      Substitute the L3FW for L2FW to make simulation quicker
#    -nocrypto	Substitute fake cryptographic routines to speed simulation
#    -noclr	Clear only the minimum amount of RAM to speed simulation
#    -debugmsg	Allow debug serial output
#    -handshake	GPIO handshake with simulation/test controller
#------------------------------------------------------------------------------
BuildRoot=~/work/bootrom
BuildDir=~/work/bootrom/build
BinDir=~/work/bootrom/binary
KeyDir=~/bin
AssyDir=~/bootrom-tools/es3-test
DropDir=~/es3-test
Zip=false
SpecialTest=false
HaveSpecialTest=false
JustBootrom=false
CryptoSuffix="-crypto"
DbgSuffix="-quiet"
HandshakeSuffix=""
DbgModeSuffix="-opt"
Ornamentation=$(bootsuffix $*)

#-----
# Process args
#-----
for arg in "$@" ; do    # arg will be each positional parameter
    if $SpecialTest; then
        # The previous arg was "-spec", so pick up the special test no.
        SpecialTestNum="${arg} "
        HaveSpecialTest=true
        SpecialTest=false
        echo "have special test $SpecialTestNum"
    elif [[ ${arg} == "-spec" ]]; then
        # Take the next arg as a special test number
        SpecialTest=true
    elif [[ ${arg} == "-justboot" ]]; then  # select target configuration
        JustBootrom=true
    elif [[ ${arg} == "-es2tsb" ]]; then  # select target configuration
        CONFIG_CHIP="es2tsb"
    elif [[ ${arg} == "-es3tsb" ]]; then  # select target configuration
        CONFIG_CHIP="es3tsb"
    elif [[ ${arg} == "-fpgatsb" ]]; then # select target configuration
        CONFIG_CHIP="fpgatsb"
    elif [[ ${arg} == "-prod" ]]; then    # Production version
        Production=${arg}
    elif [[ ${arg} == "-v" ]]; then       # TFTF verbose mode
        Verbose="${arg} "
    elif [[ ${arg} == "-dbg" ]]; then     # Build with debugging symbols
        DbgMode="${arg} "
        DbgModeSuffix="-debug"
    elif [[ ${arg} == "-zip" ]]; then     # suppress zip file generation
        Zip=true
    # Test args
    elif [[ ${arg} == "-nocrypto" ]]; then
        # Substitute fake cryptographic routines to speed simulation
        NoCrypto="${arg} "
        CryptoSuffix="-nc"
    elif [[ ${arg} == "-noclr" ]]; then
        # Clear only the minimum amount of RAM to speed simulation
        NoClr="${arg} "
    elif [[ ${arg} == "-debugmsg" ]]; then
        # Allow debug serial output
        DebugMessages="${arg} "
        DbgSuffix="-uart"
    elif [[ ${arg} == "-handshake" ]]; then
        # GPIO handshake with simulation/test controller
        Handshake="${arg} "
    elif [[ ${arg} == "-stby" ]]; then
        #    -handshake	GPIO handshake with simulation/test controller
        StandbyTest="${arg} "
    elif [[ ${arg} == "-stby-wait-svr" ]]; then
        #    -handshake	GPIO handshake with simulation/test controller
        StandbyWaitForServer="${arg} "
    elif [[ ${arg} == "-stby-gbboot" ]]; then
        #    -handshake	GPIO handshake with simulation/test controller
        GBBootServerStandby="${arg} "
    elif [[ ${arg} == "-342" ]]; then
        # Substitute the L3FW for L2FW to make simulation quicker
        Subst342="${arg} "
    else
        echo "Makeall: unknown arg $arg"
        exit 1
    fi
done

# Fill in missing chip
if [ ! $CONFIG_CHIP ]; then
    echo "CONFIG_CHIP not set, assuming $DEFAULT_CHIP_CONFIG"
    CONFIG_CHIP=$DEFAULT_CHIP_CONFIG
fi

# Parlay the chip into a bootrom suffix component
if [[ $CONFIG_CHIP == "es2tsb" ]]; then  # select target configuration
    ChipSuffix="-es2"
elif [[ $CONFIG_CHIP == "es3tsb" ]]; then  # select target configuration
    ChipSuffix=""  # default
elif [[ $CONFIG_CHIP == "fpgatsb" ]]; then # select target configuration
    ChipSuffix="-fpga"
else
    echo "Unknown chip: $CONFIG_CHIP"
    exit 1
fi


# Make sure our target folder exists
if [ ! -d $AssyDir ]
then
    echo "Creating assembly folder: $AssyDir"
    mkdir $AssyDir
fi
if [ ! -d $AssyDir/ffff ]
then
    mkdir $AssyDir/ffff
fi
if [ ! -d $AssyDir/ctrl-files ]
then
    mkdir $AssyDir/ctrl-files
fi
if [ ! -d $AssyDir/response-files ]
then
    mkdir $AssyDir/response-files
fi
if [ ! -d $AssyDir/response-dme ]
then
    mkdir $AssyDir/response-dme
fi
if [ ! -d $AssyDir/s1fw ]
then
    mkdir $AssyDir/s1fw
fi


# Compose the bulk of our "makef4 and "makeboot" arguments
F4Args="-$CONFIG_CHIP $Production -dbg -nocrypto -debugmsg -handshake $NoClr$Subst342"
F4Args="$F4Args$StandbyTest$StandbyWaitForServer$GBBootServerStandby"
StdArgs="-$CONFIG_CHIP $NoCrypto$NoClr$DebugMessages$DbgMode"
StdArgs="$StdArgs$StandbyTest$StandbyWaitForServer$GBBootServerStandby"
StdArgs="$StdArgs$ProductionS$Subst342"
if $HaveSpecialTest; then
    StdArgs="$StdArgs-spec $SpecialTestNum"
else
    StdArgs="$StdArgs$Handshake"
fi



pushd $BuildRoot

#-----
# Build the components that only need to be built once
#-----
if ! $JustBootrom; then
    # GBBOOT server build
    echo "--"
    echo "Building the GBBOOT server"
    echo "--"
    makeserver -$CONFIG_CHIP
    if [[ $? == 0 ]]; then
        mv $BuildDir/gbboot_server.bin $AssyDir/s1fw
        mv $BuildDir/gbboot_server.hex $AssyDir/s1fw
    else
        echo "Problems building GBBoot server"
        popd
        exit 1
    fi

    # Build untrusted (non-signed) FFFF
    echo "--"
    echo "Building the Untrusted (non-signed) image"
    echo "--"
    makef4 $F4Args
    if [[ $? == 0 ]]; then
        mv $BinDir/ffff.bin $AssyDir/ffff
        mv $BinDir/ffff.map $AssyDir/ffff
    else
        echo "Problems building unsigned FFFF"
        popd
        exit 1
    fi

    # Build trusted (signed) FFFF
    echo "--"
    echo "Building the Trusted (signed) image"
    echo "--"
    makef4 $F4Args -sign
    if [[ $? == 0 ]]; then
        mv $BinDir/ffff-sgn.bin $AssyDir/ffff
        mv $BinDir/ffff-sgn.map $AssyDir/ffff
    else
        echo "Problems building signed FFFF"
        popd
        exit 1
    fi
fi


#-----
# Build Bootrom
#-----
echo "--"
echo "Building the Trusted (signed) image"
echo "--"
makeboot $StdArgs
if [[ $? == 0 ]]; then
    mv $BuildDir/bootrom$Ornamentation.bin $AssyDir/s1fw
    mv $BuildDir/bootrom$Ornamentation.hex $AssyDir/s1fw
else
    echo "Problems building signed FFFF"
    popd
    exit 1
fi



#-----
# (Re)create the drop folder from the pieces in the assembly folder
#-----
# Make sure our drop folder exists
if ! $JustBootrom; then
    if [ -d $DropDir ]
    then
        echo "Removing old drop folder: $DropDir"
        rm -r $DropDir
    fi
fi

if [ ! -d $DropDir ]
then
    echo "Creating drop folder: $DropDir"
    mkdir $DropDir
fi
if [ ! -d $DropDir/efuse ]
then
    mkdir $DropDir/efuse
fi
if [ ! -d $DropDir/ffff ]
then
    mkdir $DropDir/ffff
fi
if [ ! -d $DropDir/ctrl-files ]
then
    mkdir $DropDir/ctrl-files
fi
if [ ! -d $DropDir/response-files ]
then
    mkdir $DropDir/response-files
fi
if [ ! -d $DropDir/response-dme ]
then
    mkdir $DropDir/response-dme
fi
if [ ! -d $DropDir/s1fw ]
then
    mkdir $DropDir/s1fw
fi

# Populate the drop folder
cp $AssyDir/efuse/* $DropDir/efuse
cp $AssyDir/ffff/* $DropDir/ffff
cp $AssyDir/ctrl-files/*.ctrl $DropDir/ctrl-files
cp $AssyDir/response-files/*.rsp $DropDir/response-files
cp $AssyDir/response-dme/*.rsp $DropDir/response-dme
cp $AssyDir/s1fw/* $DropDir/s1fw



# Generate the test files in the drop folder
create-bootrom-test-suite \
  --bin $AssyDir/s1fw/bootrom$Ornamentation.bin \
  --flash $AssyDir/ffff/ffff-sgn.bin \
  --desc $AssyDir/es3.tss \
  --test trusted$Ornamentation.ts \
  --out_folder $DropDir/ffff
if [[ $? != 0 ]]; then
    echo "Problems creating trusted testsuite"
    popd
    exit 1
fi

create-bootrom-test-suite \
  --bin $AssyDir/s1fw/bootrom$Ornamentation.bin \
  --flash $AssyDir/ffff/ffff.bin \
  --desc $AssyDir/es3.tss \
  --test untrusted$Ornamentation.ts \
  --out_folder $DropDir/ffff
if [[ $? != 0 ]]; then
    echo "Problems creating untrusted testsuite"
    popd
    exit 1
fi


# Create the .hex files for all of the ffff variants
echo "Generating ffff .hex files..."
pushd $DropDir/ffff
for f in *.bin
do
    FBase=`basename $f .bin`
    hexdump -v -e '/1 "%02X\n"' $FBase.bin > $FBase.hex 
done
popd


if $Zip; then
    # Zip it all up
    echo "Generating drop..."
    if [[ "${Production}" == "-prod" ]]; then
        Archive="`date +%Y%m%d-%H%M-%Z`.es3-test-prod.tar.gz"
    else
        Archive="`date +%Y%m%d-%H%M-%Z`.es3-test.tar.gz"
    fi
    tar -zcvf ~/$Archive $DropDir
    echo "Dropped to ~/$Archive"
fi

# Done
popd

