#!/bin/bash
#
# Copyright (c) 2015 Google Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the names of its
# contributors may be used to endorse or promote products derived from this
# software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#------------------------------------------------------------------------------
# Make all 3 images, their TFTF files, and bundle into an FFFF file.
#
# Usage:
#    makeall {-es2tsb | -es3tsb | -fpgatsb } {-v}
#
#    -es2tsb, -es3tsb, -fpgatsb
#                        Select the build target
#    -v                  Verbose mode on TFTF creation
#------------------------------------------------------------------------------
BuildRoot=~/work/bootrom
BuildDir=~/work/bootrom/build
BinDir=~/work/bootrom/binary
KeyDir=~/bin
AssyDir=~/bootrom-tools/es3-test
DropDir=~/es3-test
Drop2Dir=~/es3-test-drop
DbgDir=es3-test-dbg
NonDbgDir=es3-test-nodbg


#-----
# Process any args
#-----
for arg in "$@" ; do    # arg will be each positional parameter
    if [[ ${arg} == "-v" ]]; then       # TFTF verbose mode
        Verbose=${arg}
    else
        echo "Makeall: unknown arg $arg"
        exit 1
    fi
done


# Make sure our target folder exists
if [ ! -d $Drop2Dir ]
then
    echo "Creating assembly folder: $AssyDir"
    mkdir $Drop2Dir
fi
if [ ! -d $Drop2Dir/$DbgDir ]
then
    mkdir $Drop2Dir/$DbgDir
else
    rm -r $Drop2Dir/$DbgDir/*
fi
if [ ! -d $Drop2Dir/$NonDbgDir ]
then
    mkdir $Drop2Dir/$NonDbgDir
else
    rm -r $Drop2Dir/$NonDbgDir/*
fi


echo "making debug tree"
makeall -fpgatsb $Verbose
cp -r $DropDir/* $Drop2Dir/$DbgDir

echo "making non-debug tree"
makeall $* -es3tsb $Verbose
cp -r $DropDir/* $Drop2Dir/$NonDbgDir

# Zip it all up
echo "Generating drop..."
pushd ~
Archive="`date +%Y%m%d-%H%M-%Z`.es3-test.tar.gz"
tar -zcvf ./$Archive es3-test-drop
popd
echo "Dropped to ~/$Archive"

# Done

