#!/bin/bash
./create-tftf \
-v \
--code Makefile \
--name "twas twillig and the slithy toves did gyre and gimbal in the wabe" \
--data create-tftf.c \
--code Makefile --offset 0x10007000 \
--code Makefile \
--data create-tftf.c \
--load 0x10000000 \
--start 0x100000200 \
--out test.tftf


